server:
  port: 8080
  url: http://localhost:${server.port}
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  liquibase:
    enabled: true
    change-log: db/db-changelog.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: on

#springdoc:
#  swagger-ui:
#    path: ${server.url}/swagger-ui/index.html